logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
mvc:
  hiddenmethod:
    filter:
      enabled: true

# PostgreSQL
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: 1234
    url: jdbc:postgresql://localhost:5432/reborn_rb_db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# MySQL
#spring:
#  datasource:
#    driverClassName: org.postgresql.Driver
#    password: 1234
#    url: jdbc:postgresql://localhost:5432/reborn_rb_db
#    username: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
server:
  port : 8081
