logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
mvc:
  hiddenmethod:
    filter:
      enabled: true


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 12345
    url: jdbc:mysql://localhost:3306/l2_raidboss_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
server:
  port : 8081